version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "notify-discord-webhook"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6ge24nirg7k8"
s3_prefix = "notify-discord-webhook"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
