AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notify-discord-webhook

  Sample SAM Template for notify-discord-webhook
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  WebhookURL:
    Type: String
    Default: 'NOT VALID'
    Description: WebhookURL
    MinLength: 3
    MaxLength: 250
    ConstraintDescription: 'Required.'

Resources:
  NotifyDiscordFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: "084882962555.dkr.ecr.us-west-2.amazonaws.com/notify-discord-webhook"
      ImageConfig:
        Command: [ "lambda.handler" ]
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  NotifyDiscordFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt NotifyDiscordFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role"
    Value: !GetAtt NotifyDiscordFunction.Arn
